{
	"params":{
		"safemode":false,
		"name":"Generic Core",
		"version":"0.1.20130520",
		"api_version":"0.1.20130520",
		"api_auth":true,
		"api_client":"gcore",
		"api_name":"gcore",
		"trace":false,
		"support":"gcore@johnynsk.ru",
		"limit_max":300,
		"limit_default":30,
		"httproot":"http://johnynsk.ru/v1/gcore/",
		"linkroot":"http://johnynsk.ru/v1/",
		"authorize_package":"_std_auth",
		"trace_allow":[
		],
		"reference_allow":[
		]
	},
	"packages":{
		"mysqlix":{
			"location":"core/mysqlix/mysqlix.php",
			"init":"core/mysqlix/init.php",
			"params":{
				"host":"localhost",
				"user":"root",
				"password":"",
				"database":"database"
			}
		},
		"_std_object":{
			"location":"core/_std/_std_object.php",
			"dependence":[
				"mysqlix"
			]
		},
		"_std_public":{
			"location":"core/_std/_std_public.php",
			"dependence":[
				"_std_object"
			]
		},
		"gcore_client":{
			"location":"core/gcore_client/gcore_client.php",
			"init":"core/gcore_client/init.php",
			"recommends":[
				"_auth"
			]
		},
		"_std_auth":{
			"location":"core/_std/_std_auth.php",
			"init":"core/_std/_std_auth_init.php",
			"params":{
				"file_clients":"core/std_auth_clients.json"
			}
		},
		"developer":{
			"location":"core/developer/developer.php",
			"init":"core/developer/init.php",
			"public":"core/developer/developer.js",
			"dependence":[
				"_std_auth"
			]
		},
		"web":{
			"disabled":true,
			"location":"core/web/web.php",
			"init":"core/web/init.php",
			"params":{
				"theme":"themes/class/theme.php"
			}
		}
	}
}
